# Generated by Django 2.2 on 2019-04-26 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Mobileapis', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactModel',
        ),
    ]
