# Generated by Django 2.2 on 2019-05-09 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Mobileapis', '0004_airport_city_country'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Airport',
        ),
        migrations.DeleteModel(
            name='City',
        ),
        migrations.DeleteModel(
            name='Country',
        ),
    ]
